-- Equipo 1

-- BORRADO DE TABLAS
DROP TABLE competiciones CASCADE CONSTRAINTS;
DROP TABLE jornadas CASCADE CONSTRAINTS;
DROP TABLE equipos CASCADE CONSTRAINTS;
DROP TABLE jugadores CASCADE CONSTRAINTS;
DROP TABLE enfrentamientos CASCADE CONSTRAINTS;
DROP TABLE usuarios CASCADE CONSTRAINTS;

-- CREACION DE TABLAS
CREATE TABLE competiciones (
    codCompeticion NUMBER(4) GENERATED BY DEFAULT AS IDENTITY NOT NULL
        CONSTRAINT comp_cod_pk PRIMARY KEY,
    nombre VARCHAR2(50) UNIQUE,
    fechaInicio DATE NOT NULL,
    fechaFin DATE NOT NULL,
    estado VARCHAR(10) CHECK(estado IN('activo', 'inactivo'))
);

CREATE TABLE jornadas (
    codJornada NUMBER(4) GENERATED BY DEFAULT AS IDENTITY NOT NULL
        CONSTRAINT jor_cod_pk PRIMARY KEY,
    fecha DATE NOT NULL,
    competicion NUMBER(4) NOT NULL,
    CONSTRAINT jor_codComp_fk FOREIGN KEY (competicion) -- Competicion
        REFERENCES competiciones(codCompeticion)
);

CREATE TABLE equipos (
    codEquipo NUMBER(4) GENERATED BY DEFAULT AS IDENTITY NOT NULL
        CONSTRAINT equi_cod_pk PRIMARY KEY,
    nombre VARCHAR2(50) UNIQUE NOT NULL,
    fechaFundacion DATE NOT NULL
);

CREATE TABLE jugadores (
    codJugador NUMBER(4) GENERATED BY DEFAULT AS IDENTITY NOT NULL
        CONSTRAINT jug_cod_pk PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    apellidos VARCHAR2(50) NOT NULL,
    nacionalidad VARCHAR2(50) NOT NULL,
    fechaNacimiento DATE NOT NULL,
    nickname VARCHAR2(50) NOT NULL,
    rol VARCHAR2(20) CHECK(rol IN('duelista', 'iniciador', 'centinela', 
        'controlador')) NOT NULL,
    sueldo NUMBER(7, 2) NOT NULL,
    codEquipo NUMBER(4) NOT NULL,
    CONSTRAINT jug_codEqui_fk FOREIGN KEY (codEquipo) -- Equipo
        REFERENCES equipos(codEquipo)
);

CREATE TABLE enfrentamientos (
    codEnfrentamiento NUMBER(4) GENERATED BY DEFAULT AS IDENTITY NOT NULL
        CONSTRAINT enfre_cod_pk PRIMARY KEY,
    hora DATE NOT NULL,
    equipo1 NUMBER(4) NOT NULL,
    equipo2 NUMBER(4) NOT NULL,
    ganador NUMBER(4),
    jornada NUMBER(4) NOT NULL,
    CONSTRAINT enfre_equipo1_fk FOREIGN KEY (equipo1) -- Equipo 1
        REFERENCES equipos(codEquipo),
    CONSTRAINT enfre_equipo2_fk FOREIGN KEY (equipo2) -- Equipo 2
        REFERENCES equipos(codEquipo),
    CONSTRAINT enfre_ganador_fk FOREIGN KEY (ganador) -- Ganador
        REFERENCES equipos(codEquipo),
    CONSTRAINT enfre_codJor_fk FOREIGN KEY (jornada) -- Jornada
        REFERENCES jornadas(codJornada)
);

CREATE TABLE usuarios (
    id NUMBER(4) GENERATED BY DEFAULT AS IDENTITY NOT NULL
        CONSTRAINT user_id_pk PRIMARY KEY,
    email VARCHAR2(255) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    tipo VARCHAR2(5) CHECK(tipo IN('admin', 'user')) NOT NULL
);
