--VER EL ESTADO DEL TRIGGER
DESC USER_TRIGGERS;

SELECT TRIGGER_NAME,STATUS
FROM USER_TRIGGERS
WHERE UPPER(TABLE_NAME)='COMPETICIONES';

ALTER TRIGGER FECHA_COMPETICIONES_TRIGGER ENABLE;

//Insertar competiciones
INSERT INTO competiciones (nombre, fechaInicio, fechaFin, estado)
VALUES ('Liga Valorant', TO_DATE('01/05/2025', 'DD/MM/YYYY'), TO_DATE('10/05/2025', 'DD/MM/YYYY'), 'activo');
//ESTA SENTENCIA LA USO PARA VER SI MI TRIGGER FUNCIONA
INSERT INTO competiciones (nombre, fechaInicio, fechaFin, estado)
VALUES ('Torneo Test', TO_DATE('10/05/2025', 'DD/MM/YYYY'), TO_DATE('01/05/2025', 'DD/MM/YYYY'), 'activo');


-----------------------------------------------------------------
--BORRAR TODO
DELETE FROM COMPETICIONES
WHERE UPPER(NOMBRE)='LIGA VALORANT';