/* 
Trigger para que la fecha fin de competiciones no sea anterior a la de inicio y 
la de inicio no sea mayor a la de fin
*/
CREATE OR REPLACE TRIGGER FECHA_COMPETICIONES_TRIGGER
BEFORE INSERT OR UPDATE ON COMPETICIONES
FOR EACH ROW
DECLARE 
    e_fecha EXCEPTION;
BEGIN
    IF :NEW.fechaFin < :NEW.fechaInicio THEN
        RAISE e_fecha;
    END IF;

EXCEPTION   
    WHEN e_fecha THEN
        RAISE_APPLICATION_ERROR(-20001, 'LA FECHA FIN NO PUEDE SER ANTERIOR A LA FECHA DE INICIO');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20002, 'ERROR ORACLE: ' || SQLCODE || ' - ' || SQLERRM);
END FECHA_COMPETICIONES_TRIGGER;
