/*
TRIGGER PARA QUE AL INSERTAR O ACTUALIZAR LA FECHA DE JORNADAS, SEA ENTRE LA 
FECHAINICIO Y LA FECHA FIN DE LA COMPETICION
*/
CREATE OR REPLACE TRIGGER FECHA_JORNADA_TRIGGER 
BEFORE INSERT OR UPDATE OF FECHA ON JORNADAS
FOR EACH ROW
DECLARE
    V_FECHAINICIO COMPETICIONES.FECHAINICIO%TYPE;
    V_FECHAFIN COMPETICIONES.FECHAFIN%TYPE;
    E_FECHA EXCEPTION;
BEGIN
    SELECT FECHAINICIO,FECHAFIN INTO V_FECHAINICIO,V_FECHAFIN
    FROM COMPETICIONES
    WHERE COD_COMP = :NEW.COD_COMP;
    
    IF :NEW.FECHA < V_FECHAINICIO OR :NEW.FECHA > V_FECHAFIN THEN
    RAISE E_FECHA;
    END IF;
EXCEPTION
    WHEN E_FECHA THEN
    RAISE_APPLICATION_ERROR(-20001,'LA FECHA TIENE QUE ESTAR ENTRE LAS FECHAS '||
                            TO_CHAR(V_FECHAINICIO)||' - '||TO_CHAR(V_FECHAFIN));
    WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20002,'ERROR ORACLE: '||SQLCODE||'-'||TO_CHAR(SQLERRM));
END FECHA_JORNADA_TRIGGER;